DROP TRIGGER IF EXISTS AddBookToLog
DELIMITER //
CREATE TRIGGER AddBookToLog AFTER INSERT ON Books FOR EACH ROW
BEGIN
	INSERT INTO MediaLog VALUES(NEW.MediaID, 'Book', NOW(6));
END//
DELIMITER ;

DROP TRIGGER IF EXISTS AddMovieToLog
DELIMITER //
CREATE TRIGGER AddMovieToLog AFTER INSERT ON Movies FOR EACH ROW
BEGIN
	INSERT INTO MediaLog VALUES(NEW.MediaID, 'Movie', NOW(6));
END//
DELIMITER ;

DROP TRIGGER IF EXISTS AddGameToLog
DELIMITER //
CREATE TRIGGER AddGameToLog AFTER INSERT ON Games FOR EACH ROW
BEGIN
	INSERT INTO MediaLog VALUES(NEW.MediaID, 'Game', NOW(6));
END//
DELIMITER ;

DROP TRIGGER IF EXISTS AddRentToLog
DELIMITER //
CREATE TRIGGER AddRentToLog AFTER INSERT ON rentals FOR EACH ROW
BEGIN
    #DECLARE getMemberID VARCHAR(64);
    #SET getMemberID = (SELECT MemberID FROM rentals WHERE NEW.MediaID = rentals.MediaID);
	INSERT INTO RentLog VALUES(NEW.memberID, NEW.mediaID,  NOW(6));
END//
DELIMITER ;

DELETE FROM books WHERE mediaID = '1234';
# CALL AddBook('1234', 'Bastian Preisel', 'Dum bog', 'Fantasy', 'Dansk');
CALL RentMedia('0007', '3004'); 

DROP PROCEDURE IF EXISTS AddBook;
DELIMITER // 
Create Procedure AddBook (MedID INT, Author VARCHAR(45), Titel VARCHAR(45), Genre	VARCHAR(45), Lang VARCHAR(45))
BEGIN
IF (!(MediaExists(MedID))) 
Then INSERT INTO Books VALUES  (MedID, Author, Titel, Genre, Lang);
END IF;
END; //